/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.monitoring;

import javax.management.MBeanServer;
import javax.management.ObjectName;
import java.lang.management.ManagementFactory;

public class App {

    public static void main(String[] args) throws Exception {
        MBeanServer beanServer = ManagementFactory.getPlatformMBeanServer();
        EntityMXBean entity = new SimpleEntity(1, "entity");
        ObjectName entityName = new ObjectName("kz.zhanbolat.monitoring:type=entity");
        beanServer.registerMBean(entity, entityName);
        while (true) {}
    }
}
